version: '3.8'

services:
  # warehouse
  db:
    image: postgres:alpine
    shm_size: 128M
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - 8080:8080

  # lake
  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8081:9001
    volumes:
      - ./data/minio-data:/data
    command: server /data --console-address ":9001"

  # worker
  spark-master:
    build: .
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./data/spark-data:/opt/spark/data
      - ./data/spark-apps:/opt/spark/apps
      - ./data/spark-logs:/opt/spark/spark-events
      - ./conf:/opt/spark/conf
    env_file:
      - .env.spark
    ports:
      - '8082:8080'
      - '7077:7077'

  # spark-history-server:
  #   image: spark-image
  #   entrypoint: ['./entrypoint.sh', 'history']
  #   depends_on:
  #     - spark-master
  #   env_file:
  #     - .env.spark
  #   volumes:
  #     - ./data/spark-logs:/opt/spark/spark-events
  #     - ./data/conf:/opt/spark/conf
  #   ports:
  #     - '18080:18080'

  spark-worker:
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    env_file:
      - .env.spark
    volumes:
      - ./data/spark-data:/opt/spark/data
      - ./data/spark-apps:/opt/spark/apps
      - ./data/spark-logs:/opt/spark/spark-events
      - ./conf:/opt/spark/conf
